# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Q1-Q4_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Camera_Calibration_Main
import SIFT
import Stereo_Disparity_Map


class Ui_Form(object):

    def q1_1_function(self):
        Camera_Calibration_Main.Find_Corner()

    def q1_2_function(self):
        Camera_Calibration_Main.Find_The_Intrinsic_Matrix()

    def q1_3_function(self):
         select_image = self.lineEdit.text()
         Camera_Calibration_Main.Find_The_Extrinsic_Matrix(select_image)
        
    def q1_4_function(self):
        image_path = ("homework_1/Q1.Camera_Calibration/Q1_Image/")
        Camera_Calibration_Main.Find_The_Distortion_Matrix(image_path)

    def q1_5_function(self):
        Camera_Calibration_Main.Show_The_undistorted_result()

    def q4_1_function(self):
        SIFT.Show_Keypoints()
    
    def q4_2_function(self):
        SIFT.Show_Matches_Img()

    def q4_3_function(self):
        SIFT.Warp_image()

    def q3_1_function(self):
        Stereo_Disparity_Map.Stereo_Disparity_Map()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(845, 636)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 195, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(300, -10, 239, 639))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.toolButton_8 = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_8.setFont(font)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_2.addWidget(self.toolButton_8, 0, 1, 1, 1)

        ########## Q3_1 btn event ################

        self.toolButton_8.clicked.connect(self.q3_1_function)

        ########################################

        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(620, 0, 218, 639))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolButton_7 = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout_3.addWidget(self.toolButton_7, 2, 0, 1, 1)

        ########## Q4_3 btn event ################

        self.toolButton_7.clicked.connect(self.q4_3_function)

        ########################################

        self.toolButton_10 = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_10.setFont(font)
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout_3.addWidget(self.toolButton_10, 1, 0, 1, 1)

        ########## Q4_2 btn event ################

        self.toolButton_10.clicked.connect(self.q4_2_function)

        ########################################

        self.toolButton_9 = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_9.setFont(font)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout_3.addWidget(self.toolButton_9, 0, 0, 1, 1)


        ########## Q4_1 btn event ################

        self.toolButton_9.clicked.connect(self.q4_1_function)

        ########################################

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 0, 193, 639))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 0, 1, 1)

        self.toolButton_4 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 8, 0, 1, 1)

        ########## Q1_4 btn event ################

        self.toolButton_4.clicked.connect(self.q1_4_function)

        ########################################

        self.toolButton_3 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 4, 0, 1, 1)

        ########## Q1_3 btn event ################

        self.toolButton_3.clicked.connect(self.q1_3_function)

        ########################################

        self.toolButton = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 0, 1, 1)

        ########## Q1_1 btn event ################

        self.toolButton.clicked.connect(self.q1_1_function)

        ########################################

        self.toolButton_2 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 0, 1, 1)

        ########## Q1_2 btn event ################

        self.toolButton_2.clicked.connect(self.q1_2_function)

        ########################################

        self.toolButton_5 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 9, 0, 1, 1)

        ########## Q1_5 btn event ################

        self.toolButton_5.clicked.connect(self.q1_5_function)

        ########################################

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton_8.setText(_translate("Form", "3.1 Stereo Disparity Map"))
        self.toolButton_7.setText(_translate("Form", "4.3 Warp Image"))
        self.toolButton_10.setText(_translate("Form", "4.2 Maatched Keypoints"))
        self.toolButton_9.setText(_translate("Form", "4.1 Keypoints"))
        self.toolButton_4.setText(_translate("Form", "1.4 Find Distortion"))
        self.toolButton_3.setText(_translate("Form", "1.3 Find Extrinsic"))
        self.toolButton.setText(_translate("Form", "1.1 Find Corners"))
        self.toolButton_2.setText(_translate("Form", "1.2 Find Intrinsic"))
        self.toolButton_5.setText(_translate("Form", "1.5 Show Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
