# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Q5_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import VGG_main


class Ui_Form(object):

    def q5_1_funciton(self):
        VGG_main.show_Cifar10_training_img()

    def q5_2_funciton(self):
        VGG_main.print_training_hyperparameters_info()

    def q5_3_funciton(self):
        VGG_main.print_model_structe()

    def q5_4_funciton(self):
        VGG_main.show_auc_and_loss_img()

    def q5_6_funciton(self):
        VGG_main.tarin_model()


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 401, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.toolButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 0, 1, 1)

        ########## Q1 btn event ################

        self.toolButton.clicked.connect(self.q5_1_funciton)

        ########################################

        self.toolButton_4 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 4, 0, 1, 1)

        ########## Q4 btn event ################

        self.toolButton_4.clicked.connect(self.q5_4_funciton)

        ########################################

        self.toolButton_3 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 3, 0, 1, 1)

        ########## Q3 btn event ################

        self.toolButton_3.clicked.connect(self.q5_3_funciton)

        ########################################

        self.toolButton_2 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 2, 0, 1, 1)

        ########## Q2 btn event ################

        self.toolButton_2.clicked.connect(self.q5_2_funciton)

        ########################################

        self.toolButton_5 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 5, 0, 1, 1)

        ########## Q6 btn event ################

        self.toolButton_5.clicked.connect(self.q5_6_funciton)

        ########################################

        self.verticalLayout.addLayout(self.gridLayout)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(70, 0, 256, 31))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton.setText(_translate("Form", "1. Show Train Image"))
        self.toolButton_4.setText(_translate("Form", "4.Show Accuracy"))
        self.toolButton_3.setText(_translate("Form", "3.Show Model Structure"))
        self.toolButton_2.setText(_translate("Form", "2.Show HyperParameter"))
        self.toolButton_5.setText(_translate("Form", "6. Train"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">VGG16</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
